services:
  web-b2b-backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - -./env/.env.common
      - ${ENV_FILE:-./env/.env.dev}
    volumes:
      - ./server/upload:/app/upload
    expose:
      - "80"
    restart: unless-stopped
    networks:
      - beisi-shared-network

  web-b2b-frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
        NEXT_PUBLIC_DJANGO_BASE_URL: ${NEXT_PUBLIC_DJANGO_BASE_URL}
        NEXT_PUBLIC_BASE_PATH: ${NEXT_PUBLIC_BASE_PATH}
        NEXT_PUBLIC_IMAGE_DOMAINS: ${NEXT_PUBLIC_IMAGE_DOMAINS}
        NEXT_PUBLIC_TEMPLATE_ID: ${NEXT_PUBLIC_TEMPLATE_ID}
    env_file:
      - -./env/.env.common
      - ${ENV_FILE:-./env/.env.dev}
    expose:
      - "80"
    restart: unless-stopped
    networks:
      - beisi-shared-network

networks:
  beisi-shared-network:
    external: true
    name: beisi-shared-network
